In [2]:
filename = "/Users/tejasskamar/PROJECTS/Data_mining/GIT/irish-home-retrofit-prediction/BER_Residential_Data.csv"
input_file = filename
output_file = '/Users/tejasskamar/PROJECTS/Data_mining/GIT/irish-home-retrofit-prediction/cleaned_data76.parquet'

In [3]:
import pandas as pd
import random

# Calculate roughly how many rows to skip to get a 5% sample
# Assuming you have ~10 million rows, this keeps ~500k

n = sum(1 for line in open(filename)) - 1 # total number of records
s = 500000 # desired sample size
skip = sorted(random.sample(range(1, n+1), n-s))

df_sample = pd.read_csv(filename, skiprows=skip)

/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/776061744.py:11: DtypeWarning: Columns (0: StorageLosses, 1: ManuLossFactorAvail, 2: SolarHotWaterHeating, 3: ElecImmersionInSummer, 4: CombiBoiler, 5: KeepHotFacility, 6: InsulationType, 7: PrimaryCircuitLoss, 8: gsdSHRenewableResources, 9: gsdWHRenewableResources, 10: FirstEnerProdConvFactor, 11: FirstEnerConsumedComment, 12: FirstEnerConsumedDelivered, 13: FirstEnerConsumedConvFactor, 14: SecondEnerProdComment, 15: SecondPartLTotalContribution, 16: SecondEnerProdConvFactor, 17: SecondEnerConsumedComment, 18: SecondEnerConsumedDelivered, 19: ThirdEnerProdComment, 20: ThirdEnerConsumedComment) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sample = pd.read_csv(filename, skiprows=skip)

In [4]:
df_sample.describe()

,Year_of_Construction,BerRating,GroundFloorAreasq_m,UValueWall,UValueRoof,UValueFloor,UValueWindow,UvalueDoor,WallArea,RoofArea,...,ThirdWallUValue,ThirdWallAgeBandId,ThirdWallTypeId,prob_smarea_error_0corr,prob_smarea_error_100corr,RER,RenewEPnren,RenewEPren,CPC,EPC
count,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,...,90239.000000,89030.000000,90127.000000,3.828270e+05,382827.000000,240444.000000,240442.000000,240442.000000,276822.000000,276822.000000
mean,1985.664926,205.396383,117.730152,0.629052,0.367357,0.410380,2.425520,2.255344,97.264207,72.300868,...,0.752043,6.741930,6.893340,2.654561e-02,0.028293,0.191339,19246.093368,2922.084510,1.048482,0.972240
std,35.085671,154.639433,62.995995,0.549985,0.500661,0.255989,0.893812,1.059417,57.825177,52.483186,...,0.615583,3.135171,3.006461,4.059557e-02,0.027723,0.245896,16694.667990,4887.786525,0.997155,0.757093
min,1753.000000,-285.280000,6.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,5.642000e-09,0.002500,0.000000,0.000000,-38012.800000,-3.025000,-0.811000
25%,1974.000000,115.590000,79.110000,0.270000,0.130000,0.180000,1.900000,1.400000,54.980000,43.050000,...,0.320000,4.000000,4.000000,1.168070e-05,0.002500,0.000000,6326.240000,0.000000,0.309000,0.348000
50%,1998.000000,184.120000,103.000000,0.420000,0.200000,0.410000,2.590000,2.980000,89.560000,60.380000,...,0.522000,7.000000,8.000000,2.500000e-03,0.017443,0.000000,16209.200000,0.000000,0.909000,0.906000
75%,2006.000000,258.010000,138.262500,0.600000,0.390000,0.580000,2.860000,3.000000,120.000000,93.810000,...,1.100000,9.000000,10.000000,5.000000e-02,0.050000,0.403000,26273.275000,4791.602500,1.402000,1.297000
max,2026.000000,8900.850000,2331.920000,5.100000,7.000000,2.100000,9.000000,8.500000,1480.240000,940.000000,...,10.000000,12.000000,14.000000,9.675549e-01,0.400000,2.810000,604515.000000,245765.000000,21.737000,13.502000

In [5]:
missing_percentages = df_sample.isnull().sum() / len(df_sample) * 100

columns_to_drop = missing_percentages[missing_percentages > 50].index.tolist()

print("Columns with more than 50% missing values:")
for col in columns_to_drop:
    print(f"- {col}: {missing_percentages[col]:.2f}%")

Columns with more than 50% missing values:
- StorageLosses: 51.17%
- ManuLossFactorAvail: 51.17%
- SolarHotWaterHeating: 51.17%
- ElecImmersionInSummer: 51.17%
- CombiBoiler: 51.17%
- KeepHotFacility: 51.17%
- WaterStorageVolume: 51.17%
- DeclaredLossFactor: 51.17%
- TempFactorUnadj: 51.17%
- TempFactorMultiplier: 51.17%
- InsulationType: 51.17%
- InsulationThickness: 51.17%
- PrimaryCircuitLoss: 51.17%
- CombiBoilerAddLoss: 51.17%
- ElecConsumpKeepHot: 51.17%
- ApertureArea: 95.81%
- ZeroLossCollectorEff: 95.81%
- CollectorHeatLossCoEff: 95.81%
- AnnualSolarRadiation: 95.81%
- OvershadingFactor: 95.81%
- SolarStorageVolume: 95.81%
- VolumeOfPreHeatStore: 98.33%
- ElectricityConsumption: 95.81%
- gsdHSSupplHeatFraction: 98.22%
- gsdHSSupplSystemEff: 98.22%
- DistLossFactor: 98.22%
- CHPUnitHeatFraction: 98.22%
- CHPSystemType: 98.22%
- CHPElecEff: 98.22%
- CHPHeatEff: 98.22%
- CHPFuelType: 98.22%
- SupplHSFuelTypeID: 98.22%
- gsdSHRenewableResources: 99.37%
- gsdWHRenewableResources: 99.37%
- SolarHeatFraction: 98.22%
- TotalDeliveredEnergy: 65.79%
- DeliveredEnergySupplementaryWater: 62.78%
- CO2SupplementaryWater: 62.78%
- FirstEnerProdComment: 87.75%
- FirstEnerConsumedComment: 99.87%
- SecondEnerProdComment: 99.48%
- SecondEnerConsumedComment: 99.99%
- ThirdEnerProdComment: 99.96%
- ThirdEnerConsumedComment: 100.00%
- FirstBoilerFuelType: 98.22%
- FirstHeatGenPlantEff: 98.22%
- FirstPercentageHeat: 98.22%
- SecondBoilerFuelType: 98.22%
- SecondHeatGenPlantEff: 98.22%
- SecondPercentageHeat: 98.22%
- ThirdBoilerFuelType: 98.22%
- ThirdHeatGenPlantEff: 98.22%
- ThirdPercentageHeat: 98.22%
- SolarSpaceHeatingSystem: 98.22%
- TotalPrimaryEnergyFact: 98.22%
- TotalCO2Emissions: 98.22%
- SecondWallType_Description: 66.72%
- SecondWallDescription: 64.48%
- SecondWallArea: 51.34%
- SecondWallUValue: 51.34%
- SecondWallIsSemiExposed: 51.38%
- SecondWallAgeBandId: 51.83%
- SecondWallTypeId: 51.38%
- ThirdWallType_Description: 86.54%
- ThirdWallDescription: 84.98%
- ThirdWallArea: 81.95%
- ThirdWallUValue: 81.95%
- ThirdWallIsSemiExposed: 81.97%
- ThirdWallAgeBandId: 82.19%
- ThirdWallTypeId: 81.97%
- RER: 51.91%
- RenewEPnren: 51.91%
- RenewEPren: 51.91%

In [6]:
# List of columns to ignore
cols_to_drop = ['ThirdEnerConsumedComment', 'CHPFuelType', 'SolarStorageVolume'] # and so on

# When reading chunks, only use the columns you want
df_chunk = pd.read_csv(filename, usecols=lambda x: x not in cols_to_drop)

/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/1136360822.py:5: DtypeWarning: Columns (0: StorageLosses, 1: ManuLossFactorAvail, 2: SolarHotWaterHeating, 3: ElecImmersionInSummer, 4: CombiBoiler, 5: KeepHotFacility, 6: InsulationType, 7: PrimaryCircuitLoss, 8: SolarHeatFraction, 9: DeliveredLightingEnergy, 10: FirstPartLTotalContribution, 11: FirstEnerConsumedComment, 12: FirstEnerConsumedConvFactor, 13: FirstEnerConsumedCO2EmissionFactor, 14: SecondEnergyTypeId, 15: SecondPartLTotalContribution, 16: SecondEnerProdCO2EmissionFactor, 17: SecondEnerConsumedComment, 18: SecondEnerConsumedConvFactor, 19: SecondEnerConsumedCO2EmissionFactor, 20: ThirdPartLTotalContribution) have mixed types. Specify dtype option on import or set low_memory=False.
  df_chunk = pd.read_csv(filename, usecols=lambda x: x not in cols_to_drop)

In [10]:
import pandas as pd
import numpy as np

file_path = filename
chunk_size = 100000
total_rows = 0
null_counts = None

# Pass 1: Count nulls
for chunk in pd.read_csv(file_path, chunksize=chunk_size):
    if null_counts is None:
        null_counts = chunk.isnull().sum()
    else:
        null_counts += chunk.isnull().sum()
    total_rows += len(chunk)

# Calculate percentages
null_perc = (null_counts / total_rows) * 100
cols_to_drop = null_perc[null_perc > 50].index.tolist()

print(f"Total rows processed: {total_rows}")
print(f"Columns to drop (>50% null): {len(cols_to_drop)}")

/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (144,150,161) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (144,150,155,161,166) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (144,155,161) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (61,62,63,64,65,66,71,73,97,98,144,155,161,166) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (144,155,161) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (61,62,63,64,65,66,71,73,142,144,161) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (61,62,63,64,65,66,71,73,97,98,144,155,161) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (61,62,63,64,65,66,71,73,97,98,144,155,161,166) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (61,62,63,64,65,66,71,73,142,144,145,146,155) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (97,98,139,144,150,155,161,166) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (144,150,161) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (61,62,63,64,65,66,71,73,97,98,144,150,161) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (144,150,161) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):
/tmp/ipython-input-467567022.py:10: DtypeWarning: Columns (61,62,63,64,65,66,71,73,97,98,144,150,161) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=chunk_size):

Total rows processed: 1351582
Columns to drop (>50% null): 73

In [11]:
# Pass 2: Load only useful columns
# We use 'usecols' to tell pandas exactly what to grab
def select_cols(column_name):
    return column_name not in cols_to_drop

# Now you can load a sample or chunks of the "Thin" dataset
df_clean_sample = pd.read_csv(file_path, usecols=select_cols, nrows=100000)

print(f"New Shape: {df_clean_sample.shape}")

New Shape: (100000, 138)

In [18]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)

In [14]:
import pandas as pd


chunk_size = 200000

# 1. Identify columns to keep (using the logic we built)
# We'll do a quick pass to get column names and null counts
first_chunk = pd.read_csv(input_file, nrows=1)
all_columns = first_chunk.columns
null_counts = pd.Series(0, index=all_columns)
total_rows = 0

print("Scanning for nulls...")
for chunk in pd.read_csv(input_file, chunksize=chunk_size):
    null_counts += chunk.isnull().sum()
    total_rows += len(chunk)

# Define threshold (e.g., keep columns with less than 50% missing)
limit = total_rows * 0.5
cols_to_keep = null_counts[null_counts <= limit].index.tolist()

# 2. Process and Save to Parquet
print(f"Saving {len(cols_to_keep)} columns to {output_file}...")
first_pass = True

Scanning for nulls...

/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/862958028.py:14: DtypeWarning: Columns (0: FirstEnerConsumedComment, 1: SecondEnerProdComment, 2: SecondEnerConsumedComment, 3: ThirdEnerProdComment, 4: ThirdEnerConsumedComment) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=chunk_size):
/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/862958028.py:14: DtypeWarning: Columns (0: StorageLosses, 1: ManuLossFactorAvail, 2: SolarHotWaterHeating, 3: ElecImmersionInSummer, 4: CombiBoiler, 5: KeepHotFacility, 6: InsulationType, 7: PrimaryCircuitLoss, 8: gsdSHRenewableResources, 9: gsdWHRenewableResources, 10: FirstEnerConsumedComment, 11: SecondEnerProdComment, 12: SecondEnerConsumedComment, 13: ThirdEnerProdComment, 14: ThirdEnerConsumedComment) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=chunk_size):
/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/862958028.py:14: DtypeWarning: Columns (0: StorageLosses, 1: ManuLossFactorAvail, 2: SolarHotWaterHeating, 3: ElecImmersionInSummer, 4: CombiBoiler, 5: KeepHotFacility, 6: InsulationType, 7: PrimaryCircuitLoss, 8: FirstEnerConsumedComment, 9: SecondEnerConsumedComment, 10: ThirdEnerProdComment) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=chunk_size):
/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/862958028.py:14: DtypeWarning: Columns (0: StorageLosses, 1: ManuLossFactorAvail, 2: SolarHotWaterHeating, 3: ElecImmersionInSummer, 4: CombiBoiler, 5: KeepHotFacility, 6: InsulationType, 7: PrimaryCircuitLoss, 8: gsdSHRenewableResources, 9: gsdWHRenewableResources, 10: FirstEnerProdConvFactor, 11: FirstEnerConsumedComment, 12: SecondEnerProdComment, 13: SecondEnerConsumedComment, 14: ThirdEnerProdComment, 15: ThirdEnerConsumedComment) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=chunk_size):
/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/862958028.py:14: DtypeWarning: Columns (0: StorageLosses, 1: ManuLossFactorAvail, 2: SolarHotWaterHeating, 3: ElecImmersionInSummer, 4: CombiBoiler, 5: KeepHotFacility, 6: InsulationType, 7: PrimaryCircuitLoss, 8: FirstEnerProdComment, 9: FirstEnerProdConvFactor, 10: FirstEnerConsumedComment, 11: FirstEnerConsumedDelivered, 12: FirstEnerConsumedConvFactor, 13: SecondEnerProdComment, 14: SecondPartLTotalContribution, 15: SecondEnerProdConvFactor, 16: SecondEnerConsumedComment, 17: SecondEnerConsumedDelivered, 18: ThirdEnerProdComment) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=chunk_size):
/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/862958028.py:14: DtypeWarning: Columns (0: StorageLosses, 1: ManuLossFactorAvail, 2: SolarHotWaterHeating, 3: ElecImmersionInSummer, 4: CombiBoiler, 5: KeepHotFacility, 6: InsulationType, 7: PrimaryCircuitLoss, 8: gsdSHRenewableResources, 9: gsdWHRenewableResources, 10: FirstEnerConsumedComment, 11: SecondEnerProdComment, 12: ThirdEnerProdComment) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=chunk_size):
/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/862958028.py:14: DtypeWarning: Columns (0: StorageLosses, 1: ManuLossFactorAvail, 2: SolarHotWaterHeating, 3: ElecImmersionInSummer, 4: CombiBoiler, 5: KeepHotFacility, 6: InsulationType, 7: PrimaryCircuitLoss, 8: gsdSHRenewableResources, 9: gsdWHRenewableResources, 10: FirstEnerConsumedComment, 11: SecondEnerProdComment, 12: ThirdEnerProdComment) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_file, chunksize=chunk_size):

Saving 138 columns to /Users/tejasskamar/PROJECTS/Data_mining/GIT/irish-home-retrofit-prediction/cleaned_data76.parquet...

In [15]:
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq


chunk_size = 200000

# We use the cols_to_keep list we generated earlier
writer = None

print("Starting the conversion...")

for chunk in pd.read_csv(input_file, usecols=cols_to_keep, chunksize=chunk_size, low_memory=False):

    # 1. Clean the 'No' / Mixed strings in numeric columns
    for col in chunk.select_dtypes(include=['object']).columns:
        if any(word in col for word in ['Factor', 'Area', 'Vol', 'Value', 'Efficiency', 'Loss']):
            chunk[col] = pd.to_numeric(chunk[col], errors='coerce')

    # 2. Convert Pandas chunk to a PyArrow Table
    table = pa.Table.from_pandas(chunk)

    # 3. Initialize the writer on the first chunk
    if writer is None:
        writer = pq.ParquetWriter(output_file, table.schema)

    # 4. Write the chunk
    writer.write_table(table)

# 5. VERY IMPORTANT: Close the writer to finalize the file
if writer:
    writer.close()

print(f"Success! Your file is saved as {output_file}")

Starting the conversion...

/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/2663236701.py:16: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in chunk.select_dtypes(include=['object']).columns:
/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/2663236701.py:16: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in chunk.select_dtypes(include=['object']).columns:
/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/2663236701.py:16: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in chunk.select_dtypes(include=['object']).columns:
/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/2663236701.py:16: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in chunk.select_dtypes(include=['object']).columns:
/var/folders/93/1rdjv06s2k92lhsgz52t5mtm0000gn/T/ipykernel_3553/2663236701.py:16: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in chunk.select_dtypes(include=['object']).columns:

ValueError: Table schema does not match schema used to create file:
table:
CountyName: large_string
DwellingTypeDescr: large_string
Year_of_Construction: int64
TypeofRating: large_string
EnergyRating: large_string
BerRating: double
GroundFloorAreasq_m: double
UValueWall: double
UValueRoof: double
UValueFloor: double
UValueWindow: double
UvalueDoor: double
WallArea: double
RoofArea: double
FloorArea: double
WindowArea: double
DoorArea: double
NoStoreys: int64
CO2Rating: double
MainSpaceHeatingFuel: large_string
MainWaterHeatingFuel: large_string
HSMainSystemEfficiency: double
MultiDwellingMPRN: large_string
TGDLEdition: int64
MPCDERValue: double
HSEffAdjFactor: double
HSSupplHeatFraction: double
HSSupplSystemEff: double
WHMainSystemEff: double
WHEffAdjFactor: double
SupplSHFuel: double
SupplWHFuel: double
SHRenewableResources: double
WHRenewableResources: double
NoOfChimneys: double
NoOfOpenFlues: double
NoOfFansAndVents: double
NoOfFluelessGasFires: double
DraftLobby: large_string
VentilationMethod: large_string
FanPowerManuDeclaredValue: double
HeatExchangerEff: double
StructureType: large_string
SuspendedWoodenFloor: large_string
PercentageDraughtStripped: double
NoOfSidesSheltered: double
PermeabilityTest: large_string
PermeabilityTestResult: double
TempAdjustment: double
HeatSystemControlCat: int64
HeatSystemResponseCat: int64
NoCentralHeatingPumps: int64
CHBoilerThermostatControlled: large_string
NoOilBoilerHeatingPumps: int64
OBBoilerThermostatControlled: large_string
OBPumpInsideDwelling: large_string
NoGasBoilerHeatingPumps: int64
WarmAirHeatingSystem: large_string
UndergroundHeating: large_string
GroundFloorUValue: double
DistributionLosses: double
CylinderStat: large_string
CombinedCylinder: large_string
SWHPumpSolarPowered: large_string
ChargingBasisHeatConsumed: large_string
DeliveredLightingEnergy: double
DeliveredEnergyPumpsFans: double
DeliveredEnergyMainWater: double
DeliveredEnergyMainSpace: double
PrimaryEnergyLighting: double
PrimaryEnergyPumpsFans: double
PrimaryEnergyMainWater: double
PrimaryEnergyMainSpace: double
CO2Lighting: double
CO2PumpsFans: double
CO2MainWater: double
CO2MainSpace: double
GroundFloorArea: double
GroundFloorHeight: double
FirstFloorArea: double
FirstFloorHeight: double
SecondFloorArea: double
SecondFloorHeight: double
ThirdFloorArea: double
ThirdFloorHeight: double
ThermalBridgingFactor: double
ThermalMassCategory: large_string
PredominantRoofTypeArea: double
PredominantRoofType: large_string
LowEnergyLightingPercent: double
DeliveredEnergySecondarySpace: double
LivingAreaPercent: double
CO2SecondarySpace: double
PrimaryEnergySecondarySpace: double
PrimaryEnergySupplementaryWater: double
HESSchemeUpgrade: int64
RoomInRoofArea: double
PurposeOfRating: large_string
DateOfAssessment: large_string
FirstEnergyTypeId: double
FirstEnergyType_Description: large_string
FirstEnerProdDelivered: double
FirstPartLTotalContribution: double
FirstEnerProdConvFactor: double
FirstEnerProdCO2EmissionFactor: double
FirstEnerConsumedDelivered: large_string
FirstEnerConsumedConvFactor: double
FirstEnerConsumedCO2EmissionFactor: double
SecondEnergyTypeId: double
SecondEnergyType_Description: large_string
SecondEnerProdDelivered: double
SecondPartLTotalContribution: large_string
SecondEnerProdConvFactor: double
SecondEnerProdCO2EmissionFactor: double
SecondEnerConsumedDelivered: large_string
SecondEnerConsumedConvFactor: double
SecondEnerConsumedCO2EmissionFactor: double
ThirdEnergyTypeId: double
ThirdEnergyType_Description: large_string
ThirdEnerProdDelivered: double
ThirdPartLTotalContribution: double
ThirdEnerProdConvFactor: double
ThirdEnerProdCO2EmissionFactor: double
ThirdEnerConsumedDelivered: double
ThirdEnerConsumedConvFactor: double
ThirdEnerConsumedCO2EmissionFactor: double
FirstWallType_Description: large_string
FirstWallDescription: large_string
FirstWallArea: double
FirstWallUValue: double
FirstWallIsSemiExposed: large_string
FirstWallAgeBandId: double
FirstWallTypeId: double
SA_Code: large_string
prob_smarea_error_0corr: double
prob_smarea_error_100corr: double
CPC: double
EPC: double
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 8000' + 19168 vs.
file:
CountyName: large_string
DwellingTypeDescr: large_string
Year_of_Construction: int64
TypeofRating: large_string
EnergyRating: large_string
BerRating: double
GroundFloorAreasq_m: double
UValueWall: double
UValueRoof: double
UValueFloor: double
UValueWindow: double
UvalueDoor: double
WallArea: double
RoofArea: double
FloorArea: double
WindowArea: double
DoorArea: double
NoStoreys: int64
CO2Rating: double
MainSpaceHeatingFuel: large_string
MainWaterHeatingFuel: large_string
HSMainSystemEfficiency: double
MultiDwellingMPRN: large_string
TGDLEdition: int64
MPCDERValue: double
HSEffAdjFactor: double
HSSupplHeatFraction: double
HSSupplSystemEff: double
WHMainSystemEff: double
WHEffAdjFactor: double
SupplSHFuel: double
SupplWHFuel: double
SHRenewableResources: double
WHRenewableResources: double
NoOfChimneys: double
NoOfOpenFlues: double
NoOfFansAndVents: double
NoOfFluelessGasFires: double
DraftLobby: large_string
VentilationMethod: large_string
FanPowerManuDeclaredValue: double
HeatExchangerEff: double
StructureType: large_string
SuspendedWoodenFloor: large_string
PercentageDraughtStripped: double
NoOfSidesSheltered: double
PermeabilityTest: large_string
PermeabilityTestResult: double
TempAdjustment: double
HeatSystemControlCat: int64
HeatSystemResponseCat: int64
NoCentralHeatingPumps: int64
CHBoilerThermostatControlled: large_string
NoOilBoilerHeatingPumps: int64
OBBoilerThermostatControlled: large_string
OBPumpInsideDwelling: large_string
NoGasBoilerHeatingPumps: int64
WarmAirHeatingSystem: large_string
UndergroundHeating: large_string
GroundFloorUValue: double
DistributionLosses: double
CylinderStat: large_string
CombinedCylinder: large_string
SWHPumpSolarPowered: large_string
ChargingBasisHeatConsumed: large_string
DeliveredLightingEnergy: double
DeliveredEnergyPumpsFans: double
DeliveredEnergyMainWater: double
DeliveredEnergyMainSpace: double
PrimaryEnergyLighting: double
PrimaryEnergyPumpsFans: double
PrimaryEnergyMainWater: double
PrimaryEnergyMainSpace: double
CO2Lighting: double
CO2PumpsFans: double
CO2MainWater: double
CO2MainSpace: double
GroundFloorArea: double
GroundFloorHeight: double
FirstFloorArea: double
FirstFloorHeight: double
SecondFloorArea: double
SecondFloorHeight: double
ThirdFloorArea: double
ThirdFloorHeight: double
ThermalBridgingFactor: double
ThermalMassCategory: large_string
PredominantRoofTypeArea: double
PredominantRoofType: large_string
LowEnergyLightingPercent: double
DeliveredEnergySecondarySpace: double
LivingAreaPercent: double
CO2SecondarySpace: double
PrimaryEnergySecondarySpace: double
PrimaryEnergySupplementaryWater: double
HESSchemeUpgrade: int64
RoomInRoofArea: double
PurposeOfRating: large_string
DateOfAssessment: large_string
FirstEnergyTypeId: double
FirstEnergyType_Description: large_string
FirstEnerProdDelivered: double
FirstPartLTotalContribution: double
FirstEnerProdConvFactor: double
FirstEnerProdCO2EmissionFactor: double
FirstEnerConsumedDelivered: double
FirstEnerConsumedConvFactor: double
FirstEnerConsumedCO2EmissionFactor: double
SecondEnergyTypeId: double
SecondEnergyType_Description: large_string
SecondEnerProdDelivered: double
SecondPartLTotalContribution: double
SecondEnerProdConvFactor: double
SecondEnerProdCO2EmissionFactor: double
SecondEnerConsumedDelivered: double
SecondEnerConsumedConvFactor: double
SecondEnerConsumedCO2EmissionFactor: double
ThirdEnergyTypeId: double
ThirdEnergyType_Description: large_string
ThirdEnerProdDelivered: double
ThirdPartLTotalContribution: double
ThirdEnerProdConvFactor: double
ThirdEnerProdCO2EmissionFactor: double
ThirdEnerConsumedDelivered: double
ThirdEnerConsumedConvFactor: double
ThirdEnerConsumedCO2EmissionFactor: double
FirstWallType_Description: large_string
FirstWallDescription: large_string
FirstWallArea: double
FirstWallUValue: double
FirstWallIsSemiExposed: large_string
FirstWallAgeBandId: double
FirstWallTypeId: double
SA_Code: large_string
prob_smarea_error_0corr: double
prob_smarea_error_100corr: double
CPC: double
EPC: double
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' + 19177

In [22]:
chunk_size = 200000

writer = None

print("Starting robust conversion...")

for chunk in pd.read_csv(input_file, usecols=cols_to_keep, chunksize=chunk_size, low_memory=False):

    # 1. Force mixed-string columns to numbers (handling the 'No' error)
    for col in chunk.select_dtypes(include=['object']).columns:
        if any(word in col for word in ['Factor', 'Area', 'Vol', 'Value', 'Efficiency', 'Loss', 'Prod', 'Cons']):
            chunk[col] = pd.to_numeric(chunk[col], errors='coerce')

    # 2. SCHEMA FIX: Force all numeric columns to float64
    # This prevents the 'int64' vs 'double' mismatch
    for col in chunk.select_dtypes(include=['number']).columns:
        chunk[col] = chunk[col].astype('float64')

    # 3. Convert to Table
    table = pa.Table.from_pandas(chunk)

    # 4. Initialize or Write
    if writer is None:
        writer = pq.ParquetWriter(output_file, table.schema)

    writer.write_table(table)

if writer:
    writer.close()

print(f"Success! Cleaned data saved to {output_file}")

Starting robust conversion...
Success! Cleaned data saved to /content/drive/MyDrive/data_mining_class/cleaned_data.parquet

In [4]:
import pandas as pd

# This will be much faster than pd.read_csv
df = pd.read_parquet('/content/drive/MyDrive/data_mining_class/cleaned_data.parquet')

print(f"Data loaded! Shape: {df.shape}")
df.head()

Data loaded! Shape: (1351582, 138)

,CountyName,DwellingTypeDescr,Year_of_Construction,TypeofRating,EnergyRating,BerRating,GroundFloorArea(sq m),UValueWall,UValueRoof,UValueFloor,...,FirstWallArea,FirstWallUValue,FirstWallIsSemiExposed,FirstWallAgeBandId,FirstWallTypeId,SA_Code,prob_smarea_error_0corr,prob_smarea_error_100corr,CPC,EPC
0,Co. Longford,Mid-floor apartment,2006.0,Existing,D1,259.84,93.50,0.27,0.23,0.00,...,31.21,0.270,No,10.0,2.0,137045003,2.667400e-03,0.0025,NaN,NaN
1,Dublin 20,End of terrace house,1962.0,Existing,E2,347.99,92.00,2.40,0.40,0.61,...,13.62,2.400,No,4.0,7.0,267108006,4.171086e-05,0.0025,NaN,NaN
2,Co. Cork,Semi-detached house,2006.0,Existing,C1,151.68,90.14,0.27,0.20,0.28,...,89.53,0.270,No,10.0,9.0,47117004,7.010458e-06,0.0025,NaN,NaN
3,Dublin 12,House,1960.0,Existing,C1,172.22,215.60,0.40,0.22,0.36,...,74.15,0.425,No,10.0,9.0,267156004,5.562300e-07,0.0025,NaN,NaN
4,Co. Cork,Detached house,1891.0,Existing,F,422.47,165.10,1.34,0.40,0.69,...,79.67,2.100,No,1.0,1.0,None,NaN,NaN,NaN,NaN

In [7]:
import pandas as pd
import numpy as np

# (Assuming 'df' is your loaded dataframe)
# If you need to reload it, uncomment:
# df = pd.read_csv('/content/drive/MyDrive/BERPublicSearch.txt', sep='\t', on_bad_lines='skip', low_memory=False)

print(f"Initial Shape: {df.shape}")
rows_count = len(df)
threshold = 0.5 * rows_count  # 50% Threshold

print(f"\n--- 🧹 STARTING CLEANUP (Threshold: {int(threshold)} rows) ---")

# Lists to track what we drop and why (for reporting)
cols_dropped_nulls = []
cols_dropped_chars = []
cols_dropped_zeros = []
all_cols_to_drop = set()

# ==========================================
# 1. CHECK NULLS (Standard Missing Data)
# ==========================================
for col in df.columns:
    null_count = df[col].isnull().sum()
    if null_count > threshold:
        cols_dropped_nulls.append(col)
        all_cols_to_drop.add(col)

# ==========================================
# 2. CHECK SUSPICIOUS CHARS (Text Columns)
# ==========================================
text_cols = df.select_dtypes(include=['object']).columns
# We treat '0' and '0.0' as bad data in text columns too
suspicious_chars = ['.', '-', '*', '?', '0', '0.0', 'None', 'nan','none', '?', 'N/A','NAN']

for col in text_cols:
    if col in all_cols_to_drop: continue # Skip if already marked for dropping

    # Count how many rows have these bad characters
    bad_char_count = df[col].astype(str).isin(suspicious_chars).sum()

    # Combined Badness: Nulls + Suspicious Chars
    total_bad = df[col].isnull().sum() + bad_char_count

    if total_bad > threshold:
        cols_dropped_chars.append(col)
        all_cols_to_drop.add(col)

# ==========================================
# 3. CHECK ZEROS (Numeric Columns)
# ==========================================
num_cols = df.select_dtypes(include=['number']).columns

for col in num_cols:
    if col in all_cols_to_drop: continue

    zero_count = (df[col] == 0).sum()

    # Combined Badness: Nulls + Zeros
    total_bad = df[col].isnull().sum() + zero_count

    if total_bad > threshold:
        cols_dropped_zeros.append(col)
        all_cols_to_drop.add(col)

# ==========================================
# 4. EXECUTE DROP
# ==========================================
df_cleaned = df.drop(columns=list(all_cols_to_drop))

# ==========================================
# 5. REPORT
# ==========================================
print(f"\n✅ DROPPED {len(all_cols_to_drop)} COLUMNS TOTAL.")
print(f"   - {len(cols_dropped_nulls)} columns dropped due to Nulls (NaN)")
print(f"   - {len(cols_dropped_chars)} columns dropped due to Bad Chars (., *, etc)")
print(f"   - {len(cols_dropped_zeros)} columns dropped due to >50% Zeros")

print(f"\nNew Shape: {df_cleaned.shape}")

print("\n--- DROPPED COLUMNS ---")
if cols_dropped_nulls: print(f"Nulls: {cols_dropped_nulls} ")
if cols_dropped_chars: print(f"Chars: {cols_dropped_chars} ")
if cols_dropped_zeros: print(f"Zeros: {cols_dropped_zeros} ")

Initial Shape: (1351582, 138)

--- 🧹 STARTING CLEANUP (Threshold: 675791 rows) ---

✅ DROPPED 41 COLUMNS TOTAL.
   - 1 columns dropped due to Nulls (NaN)
   - 0 columns dropped due to Bad Chars (., *, etc)
   - 40 columns dropped due to >50% Zeros

New Shape: (1351582, 97)

--- DROPPED COLUMNS ---
Nulls: ['ChargingBasisHeatConsumed']
Zeros: ['TGDLEdition', 'NoOfChimneys', 'NoOfOpenFlues', 'NoOfFluelessGasFires', 'FanPowerManuDeclaredValue', 'HeatExchangerEff', 'PermeabilityTestResult', 'TempAdjustment', 'NoOilBoilerHeatingPumps', 'NoGasBoilerHeatingPumps', 'GroundFloorUValue', 'SecondFloorArea', 'SecondFloorHeight', 'ThirdFloorArea', 'ThirdFloorHeight', 'LowEnergyLightingPercent', 'PrimaryEnergySupplementaryWater', 'HESSchemeUpgrade', 'RoomInRoofArea', 'FirstEnerProdDelivered', 'FirstPartLTotalContribution', 'FirstEnerProdConvFactor', 'FirstEnerProdCO2EmissionFactor', 'FirstEnerConsumedDelivered', 'FirstEnerConsumedConvFactor', 'FirstEnerConsumedCO2EmissionFactor', 'SecondEnerProdDelivered', 'SecondPartLTotalContribution', 'SecondEnerProdConvFactor', 'SecondEnerProdCO2EmissionFactor', 'SecondEnerConsumedDelivered', 'SecondEnerConsumedConvFactor', 'SecondEnerConsumedCO2EmissionFactor', 'ThirdEnerProdDelivered', 'ThirdPartLTotalContribution', 'ThirdEnerProdConvFactor', 'ThirdEnerProdCO2EmissionFactor', 'ThirdEnerConsumedDelivered', 'ThirdEnerConsumedConvFactor', 'ThirdEnerConsumedCO2EmissionFactor']

In [8]:
import pandas as pd

# Define the output path
output_path = '/content/drive/MyDrive/data_mining_class/BER_Cleaned_Data.parquet'

print(f"Preparing to save {df_cleaned.shape[1]} columns...")

# OPTIONAL: Memory Optimization (Highly recommended for 1.3M rows)
# Converts strings to categories and 64-bit numbers to 32-bit to save RAM
for col in df_cleaned.columns:
    if df_cleaned[col].dtype == 'object':
        df_cleaned[col] = df_cleaned[col].astype('category')
    elif df_cleaned[col].dtype == 'float64':
        df_cleaned[col] = df_cleaned[col].astype('float32')
    elif df_cleaned[col].dtype == 'int64':
        df_cleaned[col] = df_cleaned[col].astype('int32')

# Save to Parquet using snappy compression (balanced speed/size)
df_cleaned.to_parquet(output_path, engine='pyarrow', compression='snappy', index=False)

print(f"✅ FINAL SUCCESS! Your cleaned data is now saved at:\n{output_path}")

Preparing to save 97 columns...
✅ FINAL SUCCESS! Your cleaned data is now saved at:
/content/drive/MyDrive/data_mining_class/BER_Cleaned_Data.parquet

In [10]:
import pandas as pd
df = pd.read_parquet('/content/drive/MyDrive/data_mining_class/BER_Cleaned_Data.parquet')

In [11]:
df.describe()

,Year_of_Construction,BerRating,GroundFloorArea(sq m),UValueWall,UValueRoof,UValueFloor,UValueWindow,UvalueDoor,WallArea,RoofArea,...,SecondEnergyTypeId,ThirdEnergyTypeId,FirstWallArea,FirstWallUValue,FirstWallAgeBandId,FirstWallTypeId,prob_smarea_error_0corr,prob_smarea_error_100corr,CPC,EPC
count,1.351582e+06,1.351582e+06,1.351582e+06,1.351582e+06,1.351582e+06,1.351582e+06,1.351582e+06,1.351582e+06,1.351582e+06,1.351582e+06,...,1.326634e+06,1.326634e+06,1.351462e+06,1.351462e+06,1.338017e+06,1.349967e+06,1.034858e+06,1.034858e+06,744328.000000,744328.000000
mean,1.985586e+03,2.059017e+02,1.176800e+02,6.307933e-01,3.681739e-01,4.105505e-01,2.426926e+00,2.256514e+00,9.720147e+01,7.223592e+01,...,1.007028e+00,2.136004e+01,8.134174e+01,6.383138e-01,7.236318e+00,6.322965e+00,2.644680e-02,2.824566e-02,1.050006,0.973411
std,3.838839e+01,1.613526e+02,6.270390e+01,5.505162e-01,5.017844e-01,2.564954e-01,8.930042e-01,1.055888e+00,5.770587e+01,5.242488e+01,...,8.942602e-02,2.344860e+04,5.180860e+01,6.010766e-01,3.191909e+00,2.949013e+00,4.091927e-02,2.789589e-02,0.998784,0.758677
min,1.753000e+03,-4.729900e+02,5.470000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.700000e-01,1.000000e+00,1.000000e-03,1.000000e-03,0.000000e+00,1.000000e+00,5.642000e-09,2.500000e-03,-3.025000,-2.947000
25%,1.974000e+03,1.160200e+02,7.908000e+01,2.700000e-01,1.300000e-01,1.800000e-01,1.900000e+00,1.400000e+00,5.487000e+01,4.304000e+01,...,1.000000e+00,1.000000e+00,4.249000e+01,2.700000e-01,5.000000e+00,4.000000e+00,1.168070e-05,2.500000e-03,0.310000,0.349000
50%,1.998000e+03,1.843100e+02,1.029600e+02,4.200000e-01,2.000000e-01,4.100000e-01,2.590000e+00,2.980000e+00,8.951000e+01,6.031000e+01,...,1.000000e+00,1.000000e+00,7.630000e+01,3.700000e-01,8.000000e+00,5.000000e+00,2.500000e-03,1.744315e-02,0.908000,0.906000
75%,2.006000e+03,2.581400e+02,1.382600e+02,6.000000e-01,3.900000e-01,5.800000e-01,2.860000e+00,3.000000e+00,1.199200e+02,9.373000e+01,...,1.000000e+00,1.000000e+00,1.024400e+02,6.000000e-01,1.000000e+01,9.000000e+00,5.000000e-02,5.000000e-02,1.405000,1.298000
max,2.104000e+03,3.213494e+04,3.546110e+03,5.650000e+00,7.140000e+00,4.970000e+00,9.000000e+00,9.000000e+00,1.480240e+03,3.701550e+03,...,3.000000e+00,2.700801e+07,1.000000e+03,9.520000e+00,1.200000e+01,1.400000e+01,9.675549e-01,4.000000e-01,21.737000,13.502000

In [12]:
df.shape

(1351582, 97)

In [14]:
cols_to_drop_description = [col for col in df.columns if 'Description' in col]

print(f"Columns to drop containing 'Description': {cols_to_drop_description}")

df_cleaned = df.drop(columns=cols_to_drop_description)

print(f"Original shape: {df.shape}")
print(f"New shape after dropping description columns: {df_cleaned.shape}")

Columns to drop containing 'Description': ['FirstEnergyType_Description', 'SecondEnergyType_Description', 'ThirdEnergyType_Description', 'FirstWallType_Description', 'FirstWallDescription']
Original shape: (1351582, 97)
New shape after dropping description columns: (1351582, 92)

In [15]:
print(df_cleaned.columns.tolist())

['CountyName', 'DwellingTypeDescr', 'Year_of_Construction', 'TypeofRating', 'EnergyRating', 'BerRating', 'GroundFloorArea(sq m)', 'UValueWall', 'UValueRoof', 'UValueFloor', 'UValueWindow', 'UvalueDoor', 'WallArea', 'RoofArea', 'FloorArea', 'WindowArea', 'DoorArea', 'NoStoreys', 'CO2Rating', 'MainSpaceHeatingFuel', 'MainWaterHeatingFuel', 'HSMainSystemEfficiency', 'MultiDwellingMPRN', 'MPCDERValue', 'HSEffAdjFactor', 'HSSupplHeatFraction', 'HSSupplSystemEff', 'WHMainSystemEff', 'WHEffAdjFactor', 'SupplSHFuel', 'SupplWHFuel', 'SHRenewableResources', 'WHRenewableResources', 'NoOfFansAndVents', 'DraftLobby', 'VentilationMethod', 'StructureType', 'SuspendedWoodenFloor', 'PercentageDraughtStripped', 'NoOfSidesSheltered', 'PermeabilityTest', 'HeatSystemControlCat', 'HeatSystemResponseCat', 'NoCentralHeatingPumps', 'CHBoilerThermostatControlled', 'OBBoilerThermostatControlled', 'OBPumpInsideDwelling', 'WarmAirHeatingSystem', 'UndergroundHeating', 'DistributionLosses', 'CylinderStat', 'CombinedCylinder', 'SWHPumpSolarPowered', 'DeliveredLightingEnergy', 'DeliveredEnergyPumpsFans', 'DeliveredEnergyMainWater', 'DeliveredEnergyMainSpace', 'PrimaryEnergyLighting', 'PrimaryEnergyPumpsFans', 'PrimaryEnergyMainWater', 'PrimaryEnergyMainSpace', 'CO2Lighting', 'CO2PumpsFans', 'CO2MainWater', 'CO2MainSpace', 'GroundFloorArea', 'GroundFloorHeight', 'FirstFloorArea', 'FirstFloorHeight', 'ThermalBridgingFactor', 'ThermalMassCategory', 'PredominantRoofTypeArea', 'PredominantRoofType', 'DeliveredEnergySecondarySpace', 'LivingAreaPercent', 'CO2SecondarySpace', 'PrimaryEnergySecondarySpace', 'PurposeOfRating', 'DateOfAssessment', 'FirstEnergyTypeId', 'SecondEnergyTypeId', 'ThirdEnergyTypeId', 'FirstWallArea', 'FirstWallUValue', 'FirstWallIsSemiExposed', 'FirstWallAgeBandId', 'FirstWallTypeId', 'SA_Code', 'prob_smarea_error_0corr', 'prob_smarea_error_100corr', 'CPC', 'EPC']

In [16]:
string_columns = df_cleaned.select_dtypes(include=['object', 'category']).columns.tolist()
print("Columns with string (object or category) data types:")
print(string_columns)

Columns with string (object or category) data types:
['CountyName', 'DwellingTypeDescr', 'TypeofRating', 'EnergyRating', 'MainSpaceHeatingFuel', 'MainWaterHeatingFuel', 'MultiDwellingMPRN', 'DraftLobby', 'VentilationMethod', 'StructureType', 'SuspendedWoodenFloor', 'PermeabilityTest', 'CHBoilerThermostatControlled', 'OBBoilerThermostatControlled', 'OBPumpInsideDwelling', 'WarmAirHeatingSystem', 'UndergroundHeating', 'CylinderStat', 'CombinedCylinder', 'SWHPumpSolarPowered', 'ThermalMassCategory', 'PredominantRoofType', 'PurposeOfRating', 'DateOfAssessment', 'FirstWallIsSemiExposed', 'SA_Code']

In [17]:
non_binary_string_columns = []

# Define the set of 'Yes'/'No' values (case-insensitive for robustness)
yes_no_values = {'yes', 'no', 'y', 'n', 'true', 'false', 't', 'f', '1', '0'}

for col in string_columns:
    # Get unique values, convert to lowercase, and drop NaN
    unique_values = df_cleaned[col].dropna().astype(str).str.lower().unique()

    # Check if all unique values are within the 'yes_no_values' set
    # or if the column is entirely empty after dropping NaNs
    if len(unique_values) == 0 or not all(uv in yes_no_values for uv in unique_values):
        non_binary_string_columns.append(col)

print("String columns with data other than just 'Yes'/'No':")
print(non_binary_string_columns)

String columns with data other than just 'Yes'/'No':
['CountyName', 'DwellingTypeDescr', 'TypeofRating', 'EnergyRating', 'MainSpaceHeatingFuel', 'MainWaterHeatingFuel', 'VentilationMethod', 'StructureType', 'SuspendedWoodenFloor', 'CHBoilerThermostatControlled', 'OBBoilerThermostatControlled', 'OBPumpInsideDwelling', 'WarmAirHeatingSystem', 'UndergroundHeating', 'CylinderStat', 'CombinedCylinder', 'SWHPumpSolarPowered', 'ThermalMassCategory', 'PredominantRoofType', 'PurposeOfRating', 'DateOfAssessment', 'SA_Code']

In [20]:
# Select only the non_binary_string_columns
df_non_binary_strings = df_cleaned[non_binary_string_columns]

# Get the first 50 rows
sample_data = df_non_binary_strings.head(1000)

# Define the output file path in Google Drive
output_csv_path = '/content/drive/MyDrive/data_mining_class/non_binary_string_sample.csv'

# Save to CSV
sample_data.to_csv(output_csv_path, index=False)

print(f"First 50 rows of non-binary string columns saved to: {output_csv_path}")

# Display the sample data
display(sample_data)

First 50 rows of non-binary string columns saved to: /content/drive/MyDrive/data_mining_class/non_binary_string_sample.csv

,CountyName,DwellingTypeDescr,TypeofRating,EnergyRating,MainSpaceHeatingFuel,MainWaterHeatingFuel,VentilationMethod,StructureType,SuspendedWoodenFloor,CHBoilerThermostatControlled,...,WarmAirHeatingSystem,UndergroundHeating,CylinderStat,CombinedCylinder,SWHPumpSolarPowered,ThermalMassCategory,PredominantRoofType,PurposeOfRating,DateOfAssessment,SA_Code
0,Co. Longford,Mid-floor apartment,Existing,D1,Electricity,Electricity,Natural vent.,Timber or Steel Frame,No,NO,...,NO,NO,NO,NO,NO,Low,Room in Roof-Insul.on side,Unknown,Apr 7 2009 12:00AM,137045003
1,Dublin 20,End of terrace house,Existing,E2,Mains Gas,Mains Gas,Natural vent.,Masonry,No,NO,...,NO,NO,NO,NO,NO,High,Pitch Roof-Insul.on Ceiling,Unknown,Apr 15 2009 12:00AM,267108006
2,Co. Cork,Semi-detached house,Existing,C1,Heating Oil,Heating Oil,Natural vent.,Timber or Steel Frame,No,YES,...,NO,NO,NO,NO,NO,Medium-low,Pitch Roof-Insul.on Ceiling,Unknown,Apr 20 2009 12:00AM,47117004
3,Dublin 12,House,Existing,C1,Mains Gas,Mains Gas,Natural vent.,Masonry,Yes (Sealed),NO,...,NO,NO,YES,YES,NO,Medium,Pitch Roof-Insul.on Rafter,Unknown,Mar 23 2009 12:00AM,267156004
4,Co. Cork,Detached house,Existing,F,Heating Oil,Electricity,Natural vent.,Masonry,No,NO,...,NO,NO,NO,NO,NO,High,Pitch Roof-Insul.on Ceiling,Unknown,Mar 15 2009 12:00AM,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Dublin 4,Maisonette,Existing,F,Mains Gas,Mains Gas,Natural vent.,Masonry,No,NO,...,NO,NO,NO,NO,NO,Medium-high,Pitch Roof-Insul.on Ceiling,Unknown,May 5 2009 12:00AM,268113005
996,Dublin 4,Mid-floor apartment,Existing,D2,Mains Gas,Electricity,Natural vent.,Masonry,No,NO,...,NO,NO,NO,NO,NO,Medium-high,NaN,Unknown,May 6 2009 12:00AM,268110012
997,Dublin 13,House,Existing,C1,Mains Gas,Mains Gas,Natural vent.,Masonry,No,YES,...,NO,NO,NO,NO,NO,Medium,Pitch Roof-Insul.on Ceiling,Unknown,May 5 2009 12:00AM,268071003
998,Dublin 13,House,Existing,C2,Mains Gas,Mains Gas,Natural vent.,Masonry,No,YES,...,NO,NO,NO,NO,NO,Medium,Pitch Roof-Insul.on Ceiling,Unknown,May 5 2009 12:00AM,268071004
999,Dublin 13,House,Existing,C1,Mains Gas,Mains Gas,Natural vent.,Masonry,No,YES,...,NO,NO,NO,NO,NO,Medium,Pitch Roof-Insul.on Ceiling,Unknown,May 5 2009 12:00AM,268071004

In [19]:
columns_with_many_unique_values_lower = []

for col in non_binary_string_columns:
    # Convert column to string type, then to lowercase, and count unique values
    unique_count = df_cleaned[col].astype(str).str.lower().nunique()

    if unique_count > 15:
        columns_with_many_unique_values_lower.append((col, unique_count))

if columns_with_many_unique_values_lower:
    print("String columns with more than 15 unique values (case-insensitive):")
    for col, count in columns_with_many_unique_values_lower:
        print(f"- {col}: {count} unique values")
else:
    print("No string columns found with more than 15 unique values (case-insensitive).")

String columns with more than 15 unique values (case-insensitive):
- CountyName: 55 unique values
- MainSpaceHeatingFuel: 22 unique values
- MainWaterHeatingFuel: 22 unique values
- DateOfAssessment: 6558 unique values
- SA_Code: 25145 unique values

In [21]:
high_cardinality = []
useful_categories = []

total_rows = len(df_cleaned)

for col in df_cleaned.select_dtypes(include=['object', 'category']).columns:
    unique_count = df_cleaned[col].nunique()

    # 1. Very High Cardinality (Likely IDs, names, or addresses)
    if unique_count > (total_rows * 0.5):
        high_cardinality.append((col, unique_count, "Likely ID/Unique"))

    # 2. High Cardinality but potentially useful
    elif unique_count > 15:
        high_cardinality.append((col, unique_count, "High Cardinality Category"))

    # 3. Standard Categories
    else:
        useful_categories.append((col, unique_count))

# Print a nice summary
print(f"{'Column Name':<30} | {'Unique':<10} | {'Type'}")
print("-" * 60)
for col, count, note in high_cardinality:
    print(f"{col:<30} | {count:<10} | {note}")

Column Name                    | Unique     | Type
------------------------------------------------------------
CountyName                     | 55         | High Cardinality Category
MainSpaceHeatingFuel           | 21         | High Cardinality Category
MainWaterHeatingFuel           | 21         | High Cardinality Category
DateOfAssessment               | 6558       | High Cardinality Category
SA_Code                        | 25144      | High Cardinality Category

In [22]:
error_columns = [col for col in df_cleaned.columns if 'error' in col.lower()]

if error_columns:
    print("Columns containing 'error' in their names:")
    for col in error_columns:
        print(f"- {col}")
else:
    print("No columns found containing 'error' in their names.")

Columns containing 'error' in their names:
- prob_smarea_error_0corr
- prob_smarea_error_100corr

In [23]:
# Extract column names from high_cardinality list
high_cardinality_cols_to_drop = [col for col, _, _ in high_cardinality]

# Combine all columns to drop
all_columns_to_drop = list(set(high_cardinality_cols_to_drop + error_columns))

print(f"Columns to be dropped (high cardinality and error columns): {all_columns_to_drop}")

# Drop the identified columns from df_cleaned
df_final_cleaned = df_cleaned.drop(columns=all_columns_to_drop)

print(f"Original shape: {df_cleaned.shape}")
print(f"New shape after dropping high cardinality and error columns: {df_final_cleaned.shape}")

Columns to be dropped (high cardinality and error columns): ['prob_smarea_error_0corr', 'MainWaterHeatingFuel', 'CountyName', 'DateOfAssessment', 'MainSpaceHeatingFuel', 'SA_Code', 'prob_smarea_error_100corr']
Original shape: (1351582, 92)
New shape after dropping high cardinality and error columns: (1351582, 85)

In [24]:
# Define the output path for the final cleaned data
final_output_path = '/content/drive/MyDrive/data_mining_class/BER_Final_Cleaned_Data.parquet'

print(f"Preparing to save {df_final_cleaned.shape[1]} columns...")

# Save to Parquet using snappy compression
df_final_cleaned.to_parquet(final_output_path, engine='pyarrow', compression='snappy', index=False)

print(f"✅ FINAL SUCCESS! Your final cleaned data is now saved at:\n{final_output_path}")

Preparing to save 85 columns...
✅ FINAL SUCCESS! Your final cleaned data is now saved at:
/content/drive/MyDrive/data_mining_class/BER_Final_Cleaned_Data.parquet

In [25]:
df_final_cleaned.shape

(1351582, 85)

In [26]:
non_string_columns = df_final_cleaned.select_dtypes(exclude=['object', 'category']).columns.tolist()
print("Columns with non-string data types:")
print(non_string_columns)

Columns with non-string data types:
['Year_of_Construction', 'BerRating', 'GroundFloorArea(sq m)', 'UValueWall', 'UValueRoof', 'UValueFloor', 'UValueWindow', 'UvalueDoor', 'WallArea', 'RoofArea', 'FloorArea', 'WindowArea', 'DoorArea', 'NoStoreys', 'CO2Rating', 'HSMainSystemEfficiency', 'MPCDERValue', 'HSEffAdjFactor', 'HSSupplHeatFraction', 'HSSupplSystemEff', 'WHMainSystemEff', 'WHEffAdjFactor', 'SupplSHFuel', 'SupplWHFuel', 'SHRenewableResources', 'WHRenewableResources', 'NoOfFansAndVents', 'PercentageDraughtStripped', 'NoOfSidesSheltered', 'HeatSystemControlCat', 'HeatSystemResponseCat', 'NoCentralHeatingPumps', 'DistributionLosses', 'DeliveredLightingEnergy', 'DeliveredEnergyPumpsFans', 'DeliveredEnergyMainWater', 'DeliveredEnergyMainSpace', 'PrimaryEnergyLighting', 'PrimaryEnergyPumpsFans', 'PrimaryEnergyMainWater', 'PrimaryEnergyMainSpace', 'CO2Lighting', 'CO2PumpsFans', 'CO2MainWater', 'CO2MainSpace', 'GroundFloorArea', 'GroundFloorHeight', 'FirstFloorArea', 'FirstFloorHeight', 'ThermalBridgingFactor', 'PredominantRoofTypeArea', 'DeliveredEnergySecondarySpace', 'LivingAreaPercent', 'CO2SecondarySpace', 'PrimaryEnergySecondarySpace', 'FirstEnergyTypeId', 'SecondEnergyTypeId', 'ThirdEnergyTypeId', 'FirstWallArea', 'FirstWallUValue', 'FirstWallAgeBandId', 'FirstWallTypeId', 'CPC', 'EPC']

In [34]:
# Select only numeric columns from your list
numeric_df = df_cleaned[non_string_columns]

# Create correlation matrix
corr_matrix = numeric_df.corr().abs()

# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# Find features with correlation greater than 0.95
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]

print(f"Suggested to drop due to high redundancy: {to_drop}")

Suggested to drop due to high redundancy: ['CO2Rating', 'WHRenewableResources', 'PrimaryEnergyLighting', 'PrimaryEnergyPumpsFans', 'PrimaryEnergyMainSpace', 'CO2Lighting', 'CO2MainSpace', 'PrimaryEnergySecondarySpace', 'FirstWallUValue', 'CPC', 'EPC']

In [28]:
# Look at correlation specifically with the target
target_correlations = numeric_df.corr()['BerRating'].sort_values(ascending=False)

# Features near 0.00 (e.g., between -0.01 and 0.01) have almost no linear
# relationship with your target and are candidates for dropping.
weak_features = target_correlations[target_correlations.abs() < 0.01]

In [29]:
weak_features

CO2PumpsFans          0.002969
NoOfSidesSheltered    0.001356
ThirdEnergyTypeId    -0.001214
SupplSHFuel          -0.002836
Name: BerRating, dtype: float64

In [9]:
import pandas as pd
import numpy as np

# List of numeric columns from your previous step
numeric_cols = ['Year_of_Construction', 'BerRating', 'GroundFloorArea(sq m)', 'UValueWall',
                'UValueRoof', 'UValueFloor', 'UValueWindow', 'UvalueDoor', 'WallArea',
                'RoofArea', 'FloorArea', 'WindowArea', 'DoorArea', 'NoStoreys', 'CO2Rating',
                'HSMainSystemEfficiency', 'MPCDERValue', 'HSEffAdjFactor', 'HSSupplHeatFraction',
                'HSSupplSystemEff', 'WHMainSystemEff', 'WHEffAdjFactor', 'SupplSHFuel',
                'SupplWHFuel', 'SHRenewableResources', 'WHRenewableResources', 'NoOfFansAndVents',
                'PercentageDraughtStripped', 'NoOfSidesSheltered', 'HeatSystemControlCat',
                'HeatSystemResponseCat', 'NoCentralHeatingPumps', 'DistributionLosses',
                'DeliveredLightingEnergy', 'DeliveredEnergyPumpsFans', 'DeliveredEnergyMainWater',
                'DeliveredEnergyMainSpace', 'PrimaryEnergyLighting', 'PrimaryEnergyPumpsFans',
                'PrimaryEnergyMainWater', 'PrimaryEnergyMainSpace', 'CO2Lighting', 'CO2PumpsFans',
                'CO2MainWater', 'CO2MainSpace', 'GroundFloorArea', 'GroundFloorHeight',
                'FirstFloorArea', 'FirstFloorHeight', 'ThermalBridgingFactor',
                'PredominantRoofTypeArea', 'DeliveredEnergySecondarySpace', 'LivingAreaPercent',
                'CO2SecondarySpace', 'PrimaryEnergySecondarySpace', 'FirstEnergyTypeId',
                'SecondEnergyTypeId', 'ThirdEnergyTypeId', 'FirstWallArea', 'FirstWallUValue',
                'FirstWallAgeBandId', 'FirstWallTypeId', 'CPC', 'EPC']

# 1. Calculate the correlation matrix
corr_matrix = df_cleaned[numeric_cols].corr().abs()

# 2. Extract pairs that are highly correlated
high_corr_pairs = []
threshold = 0.95

# Loop through the upper triangle of the matrix to avoid self-correlation and duplicates
for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if corr_matrix.iloc[i, j] >= threshold:
            col_a = corr_matrix.columns[i]
            col_b = corr_matrix.columns[j]
            score = corr_matrix.iloc[i, j]
            high_corr_pairs.append((col_a, col_b, score))

# 3. Display the results
if high_corr_pairs:
    print(f"--- Found {len(high_corr_pairs)} Twin Pairs (Corr >= {threshold}) ---")
    for col_a, col_b, score in high_corr_pairs:
        print(f"🔗 {col_a} <--> {col_b} ({score:.4f})")
else:
    print("No highly redundant pairs found.")

NameError: name 'df_cleaned' is not defined

In [10]:
# 1. Get the names of the weak features
weak_cols_list = weak_features.index.tolist()

# 2. Combine with your redundancy list
# We use a set to ensure no duplicate names if a column is in both lists
cols_to_remove = list(set(to_drop + weak_cols_list))

print(f"Total columns being pruned: {len(cols_to_remove)}")
print(f"Examples of columns to be removed: {cols_to_remove[:5]}")

# 3. Execute the drop
df_final_weak_non_string = df_final_cleaned.drop(columns=cols_to_remove)

print(f"\n✅ Clean-up Complete!")
print(f"Remaining columns: {df_final_weak_non_string.shape[1]}")

NameError: name 'weak_features' is not defined

In [11]:
df_final_weak_non_string.shape

NameError: name 'df_final_weak_non_string' is not defined

In [12]:
# Define the output path for the final cleaned data
final_output_path = '/content/drive/MyDrive/data_mining_class/BER_Final_Cleaned_Data_first_stats_corr.parquet'

print(f"Preparing to save {df_final_weak_non_string.shape[1]} columns...")

# Save to Parquet using snappy compression
df_final_weak_non_string.to_parquet(final_output_path, engine='pyarrow', compression='snappy', index=False)

print(f"✅ FINAL SUCCESS! Your final cleaned data is now saved at:\n{final_output_path}")

NameError: name 'df_final_weak_non_string' is not defined